---
title: "Cell type annotation"
authors: "Corentin Bernou, Alexandra Chicheportiche, Léa Bellenger"
output: html_notebook
---
Libraries

```{r}
library(Seurat)
library(tidyverse)
library(dplyr)
library(clustree)
```

We used selected genes from the literature to characterize the various clusters

```{r}
change_facet_name <- function(seurat_object,
                              genes_to_plot,
                              gene_format,
                              from = "external_gene_name",
                              to = "ensembl_gene_id"){
  ## Change facet names to gene name instead of gene ID of a stacked Vlnplot
  ### Inputs
  ## - seurat_object (data) : Seurat Object to use 
  ## - genes_to_plot (vector) : vector of genes names to visualize
  ## - gene_format (data) : dataframe that contains at least the type of gene id present in gene_to_plot(from) and the gene label type present in your seurat object (to) 
  ## - from (chr) : label gene type of genes_to_plot (must be the column name of the annotated dataframe)
  ## - to (chr) : label gene type of the seurat_object
  ### Output
  ## - Plot with a new facet names

  ##check if a modification is possible
  ## check if one of the target gene is a gene of the "from" column of gene_format
  test_matching <- genes_to_plot %in% gene_format[, from]
  missing_genes <- genes_to_plot[!test_matching] #names of genes if missing

  if(length(missing_genes) == length(genes_to_plot)){
    stop(paste("No matching between `genes_to_plot` parameter and", from, "column of `gene_format` dataframe.\n", "Please check your parameters."))
  } else {

    #create named vector of gene id to plot where the names are the gene id
  genes_to_plot_conversion <- gene_format[gene_format[, from] %in% genes_to_plot[test_matching], 
                                        from]
  names(genes_to_plot_conversion) <- gene_format[gene_format[, from] %in% genes_to_plot[test_matching], 
                                        to]

  #Perform Vlnplot
  vln <- VlnPlot(seurat_object, 
                 features = names(genes_to_plot_conversion),
                 stack = TRUE,
                 flip = TRUE)

  #change facet names
  vln <- vln + facet_grid(feature ~ ., labeller = as_labeller(genes_to_plot_conversion))

  #add warning if at least one missing gene
  if(length(missing_genes) > 0){  
    warning(paste("There is at least one gene missing between `genes_to_plot` parameter and", from, "column of `gene_format` dataframe.\n", "These genes were not use for the plot :", paste(missing_genes, collapse = ", "), ".\n"))
  }
  }
  return(vln)
}
```

Import objects
```{r}
SCT_obj <- readRDS("SCT_obj.rds")
Biomart_annotated <- read.csv("Biomart_annotated.csv")
```

Choose genes to display in violin plot and order clusters appropriately
```{r}
Genes_to_show <- c("Slc1a3", "Aqp4", "Gfap", "Vcam1", "S100a6", "Egfr",
                   "Ascl1", "Top2a", "Mki67", "Dcx",
                   "Robo2", "Slc17a6", "Pdgfra", "Il33",
                   "Mog", "S100b", "Dnah11", "Acta2",
                   "Flt1", "Pecam1", "Pdgfrb", "Des", "Vtn", "Fyn", "P2ry12",
                   "Cd14", "Cd3e")
clusters_order <- 
  c("29", "4", "13", "17","20","12", "15", "5","8",
    "10","19","1", "3", "7","9", "30","27","16","24","23", "6","14", 
    "21", "28","0", "2","11", "18", "25", "31", "22","26","32")

change_facet_name(seurat_object = SCT_obj, genes_to_plot = Genes_to_show)
```


Based on this gene expression patterns, we assigned cell types manually for every cluster
```{r}
cell_annotations <- c(
  "Astrocytes",
  "Astrocytes",
  "Astrocytes",
  "NSCs",
  "TAPs",
  "Cycling Prog.",
  "Cycling Prog.",
  "Cycling Prog.",
  "Cycling Prog.",
  "Cycling Prog.",
  "Neuroblasts",
  "Neuroblasts",
  "Neuroblasts",
  "Neuroblasts",
  "Neuroblasts",
  "Neurons",
  "OPCs",
  "MFOLs",
  "MFOLs",
  "Ependymal",
  "Endothelial",
  "Pericytes",
  "Pericytes",
  "Microglia",
  "Microglia",
  "Microglia",
  "Microglia",
  "Microglia",
  "Microglia",
  "Immune",
  "Immune",
  "Immune",
  "Immune"
)

names(cell_annotations) <- as.factor(clusters_order)
Idents(FBL_irr) <- "clusters"

SCT_obj <- RenameIdents(SCT_obj, cell_annotations_irr)

SCT_obj <- AddMetaData(SCT_obj, 
                       metadata =  Idents(FBL_irr), 
                       col.name = "Cell_Type")

saveRDS(object = SCT_obj, file = "Objects/SCT_obj.rds")
```

Representation by Cell Type and marker expression by Cell Type (Figure 3. C then B):
```{r}
UMAPPlot(SCT_obj, group.by = "Cell_Type", label = T, pt.size = 10) + NoLegend()
Idents(SCT_obj) <- "Cell_Type"
change_facet_name(SCT_obj, genes_to_plot = Genes_to_show)
```




